# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.8.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.lifecycle_rule import LifecycleRule

class TestLifecycleRule(unittest.TestCase):
    """LifecycleRule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LifecycleRule:
        """Test LifecycleRule
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LifecycleRule`
        """
        model = LifecycleRule()
        if include_optional:
            return LifecycleRule(
                id = '',
                name = '',
                content_type = 'authentik_core.application',
                object_id = '',
                interval = '',
                grace_period = '',
                reviewer_groups = [
                    ''
                    ],
                reviewer_groups_obj = [
                    authentik_client.models.partial_group.PartialGroup(
                        pk = '', 
                        num_pk = 56, 
                        name = '', 
                        is_superuser = True, 
                        attributes = {
                            'key' : null
                            }, )
                    ],
                min_reviewers = 0,
                min_reviewers_is_per_group = True,
                reviewers = [
                    ''
                    ],
                reviewers_obj = [
                    authentik_client.models.partial_user.PartialUser(
                        pk = 56, 
                        username = 'A', 
                        name = '', 
                        is_active = True, 
                        last_login = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        email = '', 
                        attributes = {
                            'key' : null
                            }, 
                        uid = '', )
                    ],
                notification_transports = [
                    ''
                    ],
                target_verbose = ''
            )
        else:
            return LifecycleRule(
                id = '',
                name = '',
                content_type = 'authentik_core.application',
                reviewer_groups_obj = [
                    authentik_client.models.partial_group.PartialGroup(
                        pk = '', 
                        num_pk = 56, 
                        name = '', 
                        is_superuser = True, 
                        attributes = {
                            'key' : null
                            }, )
                    ],
                reviewers = [
                    ''
                    ],
                reviewers_obj = [
                    authentik_client.models.partial_user.PartialUser(
                        pk = 56, 
                        username = 'A', 
                        name = '', 
                        is_active = True, 
                        last_login = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        email = '', 
                        attributes = {
                            'key' : null
                            }, 
                        uid = '', )
                    ],
                target_verbose = '',
        )
        """

    def testLifecycleRule(self):
        """Test LifecycleRule"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
