# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.8.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.user_switch_response import UserSwitchResponse

class TestUserSwitchResponse(unittest.TestCase):
    """UserSwitchResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserSwitchResponse:
        """Test UserSwitchResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserSwitchResponse`
        """
        model = UserSwitchResponse()
        if include_optional:
            return UserSwitchResponse(
                redirect = ''
            )
        else:
            return UserSwitchResponse(
                redirect = '',
        )
        """

    def testUserSwitchResponse(self):
        """Test UserSwitchResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
