# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.2.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.patched_ws_federation_provider_request import PatchedWSFederationProviderRequest

class TestPatchedWSFederationProviderRequest(unittest.TestCase):
    """PatchedWSFederationProviderRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PatchedWSFederationProviderRequest:
        """Test PatchedWSFederationProviderRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PatchedWSFederationProviderRequest`
        """
        model = PatchedWSFederationProviderRequest()
        if include_optional:
            return PatchedWSFederationProviderRequest(
                name = '0',
                authentication_flow = '',
                authorization_flow = '',
                invalidation_flow = '',
                property_mappings = [
                    ''
                    ],
                reply_url = '0',
                assertion_valid_not_before = '0',
                assertion_valid_not_on_or_after = '0',
                session_valid_not_on_or_after = '0',
                name_id_mapping = '',
                authn_context_class_ref_mapping = '',
                digest_algorithm = 'http://www.w3.org/2000/09/xmldsig#sha1',
                signature_algorithm = 'http://www.w3.org/2000/09/xmldsig#rsa-sha1',
                signing_kp = '',
                encryption_kp = '',
                sign_assertion = True,
                sign_logout_request = True,
                default_name_id_policy = 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress'
            )
        else:
            return PatchedWSFederationProviderRequest(
        )
        """

    def testPatchedWSFederationProviderRequest(self):
        """Test PatchedWSFederationProviderRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
