# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.8.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.offboarding_action_enum import OffboardingActionEnum

class TestOffboardingActionEnum(unittest.TestCase):
    """OffboardingActionEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOffboardingActionEnum(self):
        """Test OffboardingActionEnum"""
        # inst = OffboardingActionEnum()

if __name__ == '__main__':
    unittest.main()
