# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.5.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.geo_ip_policy_countries_obj_inner import GeoIPPolicyCountriesObjInner

class TestGeoIPPolicyCountriesObjInner(unittest.TestCase):
    """GeoIPPolicyCountriesObjInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GeoIPPolicyCountriesObjInner:
        """Test GeoIPPolicyCountriesObjInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GeoIPPolicyCountriesObjInner`
        """
        model = GeoIPPolicyCountriesObjInner()
        if include_optional:
            return GeoIPPolicyCountriesObjInner(
                code = '01',
                name = ''
            )
        else:
            return GeoIPPolicyCountriesObjInner(
                code = '01',
                name = '',
        )
        """

    def testGeoIPPolicyCountriesObjInner(self):
        """Test GeoIPPolicyCountriesObjInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
