# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.2.1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.lifecycle_iteration_request import LifecycleIterationRequest

class TestLifecycleIterationRequest(unittest.TestCase):
    """LifecycleIterationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LifecycleIterationRequest:
        """Test LifecycleIterationRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LifecycleIterationRequest`
        """
        model = LifecycleIterationRequest()
        if include_optional:
            return LifecycleIterationRequest(
                content_type = 'authentik_core.application'
            )
        else:
            return LifecycleIterationRequest(
                content_type = 'authentik_core.application',
        )
        """

    def testLifecycleIterationRequest(self):
        """Test LifecycleIterationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
