# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.5.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.paginated_apple_independent_secure_enclave_list import PaginatedAppleIndependentSecureEnclaveList

class TestPaginatedAppleIndependentSecureEnclaveList(unittest.TestCase):
    """PaginatedAppleIndependentSecureEnclaveList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedAppleIndependentSecureEnclaveList:
        """Test PaginatedAppleIndependentSecureEnclaveList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedAppleIndependentSecureEnclaveList`
        """
        model = PaginatedAppleIndependentSecureEnclaveList()
        if include_optional:
            return PaginatedAppleIndependentSecureEnclaveList(
                pagination = authentik_client.models.pagination.Pagination(
                    next = 1.337, 
                    previous = 1.337, 
                    count = 1.337, 
                    current = 1.337, 
                    total_pages = 1.337, 
                    start_index = 1.337, 
                    end_index = 1.337, ),
                results = [
                    authentik_client.models.apple_independent_secure_enclave.AppleIndependentSecureEnclave(
                        uuid = '', 
                        user = 56, 
                        apple_secure_enclave_key = '', 
                        apple_enclave_key_id = '', 
                        device_type = '', )
                    ],
                autocomplete = {
                    'key' : null
                    }
            )
        else:
            return PaginatedAppleIndependentSecureEnclaveList(
                pagination = authentik_client.models.pagination.Pagination(
                    next = 1.337, 
                    previous = 1.337, 
                    count = 1.337, 
                    current = 1.337, 
                    total_pages = 1.337, 
                    start_index = 1.337, 
                    end_index = 1.337, ),
                results = [
                    authentik_client.models.apple_independent_secure_enclave.AppleIndependentSecureEnclave(
                        uuid = '', 
                        user = 56, 
                        apple_secure_enclave_key = '', 
                        apple_enclave_key_id = '', 
                        device_type = '', )
                    ],
                autocomplete = {
                    'key' : null
                    },
        )
        """

    def testPaginatedAppleIndependentSecureEnclaveList(self):
        """Test PaginatedAppleIndependentSecureEnclaveList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
