# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.8.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.request_rule_child_binding import RequestRuleChildBinding

class TestRequestRuleChildBinding(unittest.TestCase):
    """RequestRuleChildBinding unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestRuleChildBinding:
        """Test RequestRuleChildBinding
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestRuleChildBinding`
        """
        model = RequestRuleChildBinding()
        if include_optional:
            return RequestRuleChildBinding(
                uuid = '',
                binding = '',
                target = ''
            )
        else:
            return RequestRuleChildBinding(
                binding = '',
                target = '',
        )
        """

    def testRequestRuleChildBinding(self):
        """Test RequestRuleChildBinding"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
