# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.2.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.lifecycle_iteration_state_enum import LifecycleIterationStateEnum

class TestLifecycleIterationStateEnum(unittest.TestCase):
    """LifecycleIterationStateEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLifecycleIterationStateEnum(self):
        """Test LifecycleIterationStateEnum"""
        # inst = LifecycleIterationStateEnum()

if __name__ == '__main__':
    unittest.main()
