# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.2.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.fleet_connector import FleetConnector

class TestFleetConnector(unittest.TestCase):
    """FleetConnector unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FleetConnector:
        """Test FleetConnector
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FleetConnector`
        """
        model = FleetConnector()
        if include_optional:
            return FleetConnector(
                connector_uuid = '',
                name = '',
                enabled = True,
                component = '',
                verbose_name = '',
                verbose_name_plural = '',
                meta_model_name = '',
                url = '',
                headers_mapping = '',
                map_users = True,
                map_teams_access_group = True
            )
        else:
            return FleetConnector(
                name = '',
                component = '',
                verbose_name = '',
                verbose_name_plural = '',
                meta_model_name = '',
                url = '',
        )
        """

    def testFleetConnector(self):
        """Test FleetConnector"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
