# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.5.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.apple_independent_secure_enclave import AppleIndependentSecureEnclave

class TestAppleIndependentSecureEnclave(unittest.TestCase):
    """AppleIndependentSecureEnclave unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppleIndependentSecureEnclave:
        """Test AppleIndependentSecureEnclave
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppleIndependentSecureEnclave`
        """
        model = AppleIndependentSecureEnclave()
        if include_optional:
            return AppleIndependentSecureEnclave(
                uuid = '',
                user = 56,
                apple_secure_enclave_key = '',
                apple_enclave_key_id = '',
                device_type = ''
            )
        else:
            return AppleIndependentSecureEnclave(
                user = 56,
                apple_secure_enclave_key = '',
                apple_enclave_key_id = '',
                device_type = '',
        )
        """

    def testAppleIndependentSecureEnclave(self):
        """Test AppleIndependentSecureEnclave"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
