# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.8.0-rc7
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.agent_create_request import AgentCreateRequest

class TestAgentCreateRequest(unittest.TestCase):
    """AgentCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentCreateRequest:
        """Test AgentCreateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentCreateRequest`
        """
        model = AgentCreateRequest()
        if include_optional:
            return AgentCreateRequest(
                parent = 56,
                label = '',
                expiring = True,
                expires = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                policy_behavior = 'mirror'
            )
        else:
            return AgentCreateRequest(
        )
        """

    def testAgentCreateRequest(self):
        """Test AgentCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
