# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.5.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.web_authn_hint_enum import WebAuthnHintEnum

class TestWebAuthnHintEnum(unittest.TestCase):
    """WebAuthnHintEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWebAuthnHintEnum(self):
        """Test WebAuthnHintEnum"""
        # inst = WebAuthnHintEnum()

if __name__ == '__main__':
    unittest.main()
