# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.5.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.patched_settings_request_flags import PatchedSettingsRequestFlags

class TestPatchedSettingsRequestFlags(unittest.TestCase):
    """PatchedSettingsRequestFlags unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PatchedSettingsRequestFlags:
        """Test PatchedSettingsRequestFlags
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PatchedSettingsRequestFlags`
        """
        model = PatchedSettingsRequestFlags()
        if include_optional:
            return PatchedSettingsRequestFlags(
                core_default_app_access = True,
                enterprise_audit_include_expanded_diff = True,
                flows_continuous_login = True,
                flows_refresh_others = True
            )
        else:
            return PatchedSettingsRequestFlags(
                core_default_app_access = True,
                enterprise_audit_include_expanded_diff = True,
                flows_continuous_login = True,
                flows_refresh_others = True,
        )
        """

    def testPatchedSettingsRequestFlags(self):
        """Test PatchedSettingsRequestFlags"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
