# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.2.0-rc3
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.reviewer_user import ReviewerUser

class TestReviewerUser(unittest.TestCase):
    """ReviewerUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReviewerUser:
        """Test ReviewerUser
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReviewerUser`
        """
        model = ReviewerUser()
        if include_optional:
            return ReviewerUser(
                pk = 56,
                uuid = '',
                username = 'A',
                name = ''
            )
        else:
            return ReviewerUser(
                pk = 56,
                uuid = '',
                username = 'A',
                name = '',
        )
        """

    def testReviewerUser(self):
        """Test ReviewerUser"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
