# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.8.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.paginated_grant_request_list import PaginatedGrantRequestList

class TestPaginatedGrantRequestList(unittest.TestCase):
    """PaginatedGrantRequestList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedGrantRequestList:
        """Test PaginatedGrantRequestList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedGrantRequestList`
        """
        model = PaginatedGrantRequestList()
        if include_optional:
            return PaginatedGrantRequestList(
                pagination = authentik_client.models.pagination.Pagination(
                    next = 1.337, 
                    previous = 1.337, 
                    count = 1.337, 
                    current = 1.337, 
                    total_pages = 1.337, 
                    start_index = 1.337, 
                    end_index = 1.337, ),
                results = [
                    authentik_client.models.grant_request.GrantRequest(
                        created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_by = null, 
                        requester_data = {
                            'key' : null
                            }, 
                        fulfiller_data = {
                            'key' : null
                            }, 
                        revoked_by = null, 
                        is_active = True, 
                        expires = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        status = null, 
                        targets = [
                            ''
                            ], 
                        target_objs = [
                            authentik_client.models.requestable_target.RequestableTarget(
                                verbose_name = '', 
                                verbose_name_plural = '', 
                                meta_model_name = '', 
                                pbm_uuid = '', 
                                label = '', 
                                parent = null, )
                            ], 
                        uuid = '', )
                    ],
                autocomplete = {
                    'key' : null
                    }
            )
        else:
            return PaginatedGrantRequestList(
                pagination = authentik_client.models.pagination.Pagination(
                    next = 1.337, 
                    previous = 1.337, 
                    count = 1.337, 
                    current = 1.337, 
                    total_pages = 1.337, 
                    start_index = 1.337, 
                    end_index = 1.337, ),
                results = [
                    authentik_client.models.grant_request.GrantRequest(
                        created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_by = null, 
                        requester_data = {
                            'key' : null
                            }, 
                        fulfiller_data = {
                            'key' : null
                            }, 
                        revoked_by = null, 
                        is_active = True, 
                        expires = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        status = null, 
                        targets = [
                            ''
                            ], 
                        target_objs = [
                            authentik_client.models.requestable_target.RequestableTarget(
                                verbose_name = '', 
                                verbose_name_plural = '', 
                                meta_model_name = '', 
                                pbm_uuid = '', 
                                label = '', 
                                parent = null, )
                            ], 
                        uuid = '', )
                    ],
                autocomplete = {
                    'key' : null
                    },
        )
        """

    def testPaginatedGrantRequestList(self):
        """Test PaginatedGrantRequestList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
