# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.8.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.paginated_request_rule_list import PaginatedRequestRuleList

class TestPaginatedRequestRuleList(unittest.TestCase):
    """PaginatedRequestRuleList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedRequestRuleList:
        """Test PaginatedRequestRuleList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedRequestRuleList`
        """
        model = PaginatedRequestRuleList()
        if include_optional:
            return PaginatedRequestRuleList(
                pagination = authentik_client.models.pagination.Pagination(
                    next = 1.337, 
                    previous = 1.337, 
                    count = 1.337, 
                    current = 1.337, 
                    total_pages = 1.337, 
                    start_index = 1.337, 
                    end_index = 1.337, ),
                results = [
                    authentik_client.models.request_rule.RequestRule(
                        uuid = '', 
                        pbm_uuid = '', 
                        policy_engine_mode = 'all', 
                        name = '', 
                        targets = [
                            ''
                            ], 
                        notification_transports = [
                            ''
                            ], 
                        notification_mode = 'all', 
                        min_reviewers = 0, 
                        min_reviewers_is_per_group = True, 
                        request_flow = '', )
                    ],
                autocomplete = {
                    'key' : null
                    }
            )
        else:
            return PaginatedRequestRuleList(
                pagination = authentik_client.models.pagination.Pagination(
                    next = 1.337, 
                    previous = 1.337, 
                    count = 1.337, 
                    current = 1.337, 
                    total_pages = 1.337, 
                    start_index = 1.337, 
                    end_index = 1.337, ),
                results = [
                    authentik_client.models.request_rule.RequestRule(
                        uuid = '', 
                        pbm_uuid = '', 
                        policy_engine_mode = 'all', 
                        name = '', 
                        targets = [
                            ''
                            ], 
                        notification_transports = [
                            ''
                            ], 
                        notification_mode = 'all', 
                        min_reviewers = 0, 
                        min_reviewers_is_per_group = True, 
                        request_flow = '', )
                    ],
                autocomplete = {
                    'key' : null
                    },
        )
        """

    def testPaginatedRequestRuleList(self):
        """Test PaginatedRequestRuleList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
