# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.8.0-rc7
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.policy_behavior_enum import PolicyBehaviorEnum

class TestPolicyBehaviorEnum(unittest.TestCase):
    """PolicyBehaviorEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPolicyBehaviorEnum(self):
        """Test PolicyBehaviorEnum"""
        # inst = PolicyBehaviorEnum()

if __name__ == '__main__':
    unittest.main()
