# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.5.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.patched_account_lockdown_stage_request import PatchedAccountLockdownStageRequest

class TestPatchedAccountLockdownStageRequest(unittest.TestCase):
    """PatchedAccountLockdownStageRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PatchedAccountLockdownStageRequest:
        """Test PatchedAccountLockdownStageRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PatchedAccountLockdownStageRequest`
        """
        model = PatchedAccountLockdownStageRequest()
        if include_optional:
            return PatchedAccountLockdownStageRequest(
                name = '0',
                deactivate_user = True,
                set_unusable_password = True,
                delete_sessions = True,
                revoke_tokens = True,
                self_service_completion_flow = ''
            )
        else:
            return PatchedAccountLockdownStageRequest(
        )
        """

    def testPatchedAccountLockdownStageRequest(self):
        """Test PatchedAccountLockdownStageRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
