# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.8.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.o_auth2_dynamic_client_registration import OAuth2DynamicClientRegistration

class TestOAuth2DynamicClientRegistration(unittest.TestCase):
    """OAuth2DynamicClientRegistration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OAuth2DynamicClientRegistration:
        """Test OAuth2DynamicClientRegistration
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OAuth2DynamicClientRegistration`
        """
        model = OAuth2DynamicClientRegistration()
        if include_optional:
            return OAuth2DynamicClientRegistration(
                pbm_uuid = '',
                provider = 56,
                default_application_group = '',
                override_authorization_flow = '',
                override_invalidation_flow = '',
                override_property_mappings = [
                    ''
                    ],
                access_token_validity = '',
                refresh_token_validity = '',
                allowed_grant_types = [
                    'authorization_code'
                    ],
                policy_engine_mode = 'all'
            )
        else:
            return OAuth2DynamicClientRegistration(
                pbm_uuid = '',
                provider = 56,
        )
        """

    def testOAuth2DynamicClientRegistration(self):
        """Test OAuth2DynamicClientRegistration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
