# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.8.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.object_attribute_type_enum import ObjectAttributeTypeEnum

class TestObjectAttributeTypeEnum(unittest.TestCase):
    """ObjectAttributeTypeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testObjectAttributeTypeEnum(self):
        """Test ObjectAttributeTypeEnum"""
        # inst = ObjectAttributeTypeEnum()

if __name__ == '__main__':
    unittest.main()
