# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.8.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.paginated_user_offboarding_list import PaginatedUserOffboardingList

class TestPaginatedUserOffboardingList(unittest.TestCase):
    """PaginatedUserOffboardingList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedUserOffboardingList:
        """Test PaginatedUserOffboardingList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedUserOffboardingList`
        """
        model = PaginatedUserOffboardingList()
        if include_optional:
            return PaginatedUserOffboardingList(
                pagination = authentik_client.models.pagination.Pagination(
                    next = 1.337, 
                    previous = 1.337, 
                    count = 1.337, 
                    current = 1.337, 
                    total_pages = 1.337, 
                    start_index = 1.337, 
                    end_index = 1.337, ),
                results = [
                    authentik_client.models.user_offboarding.UserOffboarding(
                        id = '', 
                        user = 56, 
                        user_obj = null, 
                        scheduled_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        action = 'deactivate', 
                        revoke_sessions = True, 
                        revoke_tokens = True, 
                        status = null, 
                        created_by_obj = null, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        executed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                autocomplete = {
                    'key' : null
                    }
            )
        else:
            return PaginatedUserOffboardingList(
                pagination = authentik_client.models.pagination.Pagination(
                    next = 1.337, 
                    previous = 1.337, 
                    count = 1.337, 
                    current = 1.337, 
                    total_pages = 1.337, 
                    start_index = 1.337, 
                    end_index = 1.337, ),
                results = [
                    authentik_client.models.user_offboarding.UserOffboarding(
                        id = '', 
                        user = 56, 
                        user_obj = null, 
                        scheduled_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        action = 'deactivate', 
                        revoke_sessions = True, 
                        revoke_tokens = True, 
                        status = null, 
                        created_by_obj = null, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        executed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                autocomplete = {
                    'key' : null
                    },
        )
        """

    def testPaginatedUserOffboardingList(self):
        """Test PaginatedUserOffboardingList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
