# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.2.0-rc5
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.review import Review

class TestReview(unittest.TestCase):
    """Review unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Review:
        """Test Review
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Review`
        """
        model = Review()
        if include_optional:
            return Review(
                id = '',
                iteration = '',
                reviewer = authentik_client.models.reviewer_user.ReviewerUser(
                    pk = 56, 
                    uuid = '', 
                    username = 'A', 
                    name = '', ),
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                note = ''
            )
        else:
            return Review(
                id = '',
                iteration = '',
                reviewer = authentik_client.models.reviewer_user.ReviewerUser(
                    pk = 56, 
                    uuid = '', 
                    username = 'A', 
                    name = '', ),
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testReview(self):
        """Test Review"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
