# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.8.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.api.requests_api import RequestsApi


class TestRequestsApi(unittest.TestCase):
    """RequestsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RequestsApi()

    def tearDown(self) -> None:
        pass

    def test_requests_grant_requests_create(self) -> None:
        """Test case for requests_grant_requests_create

        """
        pass

    def test_requests_grant_requests_destroy(self) -> None:
        """Test case for requests_grant_requests_destroy

        """
        pass

    def test_requests_grant_requests_fulfill_partial_update(self) -> None:
        """Test case for requests_grant_requests_fulfill_partial_update

        """
        pass

    def test_requests_grant_requests_list(self) -> None:
        """Test case for requests_grant_requests_list

        """
        pass

    def test_requests_grant_requests_pending_review_list(self) -> None:
        """Test case for requests_grant_requests_pending_review_list

        """
        pass

    def test_requests_grant_requests_retrieve(self) -> None:
        """Test case for requests_grant_requests_retrieve

        """
        pass

    def test_requests_grant_requests_revoke_destroy(self) -> None:
        """Test case for requests_grant_requests_revoke_destroy

        """
        pass

    def test_requests_rule_bindings_create(self) -> None:
        """Test case for requests_rule_bindings_create

        """
        pass

    def test_requests_rule_bindings_destroy(self) -> None:
        """Test case for requests_rule_bindings_destroy

        """
        pass

    def test_requests_rule_bindings_list(self) -> None:
        """Test case for requests_rule_bindings_list

        """
        pass

    def test_requests_rule_bindings_partial_update(self) -> None:
        """Test case for requests_rule_bindings_partial_update

        """
        pass

    def test_requests_rule_bindings_retrieve(self) -> None:
        """Test case for requests_rule_bindings_retrieve

        """
        pass

    def test_requests_rule_bindings_update(self) -> None:
        """Test case for requests_rule_bindings_update

        """
        pass

    def test_requests_rule_bindings_used_by_list(self) -> None:
        """Test case for requests_rule_bindings_used_by_list

        """
        pass

    def test_requests_rule_child_bindings_create(self) -> None:
        """Test case for requests_rule_child_bindings_create

        """
        pass

    def test_requests_rule_child_bindings_destroy(self) -> None:
        """Test case for requests_rule_child_bindings_destroy

        """
        pass

    def test_requests_rule_child_bindings_list(self) -> None:
        """Test case for requests_rule_child_bindings_list

        """
        pass

    def test_requests_rule_child_bindings_partial_update(self) -> None:
        """Test case for requests_rule_child_bindings_partial_update

        """
        pass

    def test_requests_rule_child_bindings_retrieve(self) -> None:
        """Test case for requests_rule_child_bindings_retrieve

        """
        pass

    def test_requests_rule_child_bindings_update(self) -> None:
        """Test case for requests_rule_child_bindings_update

        """
        pass

    def test_requests_rule_child_bindings_used_by_list(self) -> None:
        """Test case for requests_rule_child_bindings_used_by_list

        """
        pass

    def test_requests_rules_create(self) -> None:
        """Test case for requests_rules_create

        """
        pass

    def test_requests_rules_destroy(self) -> None:
        """Test case for requests_rules_destroy

        """
        pass

    def test_requests_rules_list(self) -> None:
        """Test case for requests_rules_list

        """
        pass

    def test_requests_rules_partial_update(self) -> None:
        """Test case for requests_rules_partial_update

        """
        pass

    def test_requests_rules_retrieve(self) -> None:
        """Test case for requests_rules_retrieve

        """
        pass

    def test_requests_rules_update(self) -> None:
        """Test case for requests_rules_update

        """
        pass

    def test_requests_rules_used_by_list(self) -> None:
        """Test case for requests_rules_used_by_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
