# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.8.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.paginated_request_rule_binding_list import PaginatedRequestRuleBindingList

class TestPaginatedRequestRuleBindingList(unittest.TestCase):
    """PaginatedRequestRuleBindingList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedRequestRuleBindingList:
        """Test PaginatedRequestRuleBindingList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedRequestRuleBindingList`
        """
        model = PaginatedRequestRuleBindingList()
        if include_optional:
            return PaginatedRequestRuleBindingList(
                pagination = authentik_client.models.pagination.Pagination(
                    next = 1.337, 
                    previous = 1.337, 
                    count = 1.337, 
                    current = 1.337, 
                    total_pages = 1.337, 
                    start_index = 1.337, 
                    end_index = 1.337, ),
                results = [
                    authentik_client.models.request_rule_binding.RequestRuleBinding(
                        uuid = '', 
                        pbm_uuid = '', 
                        policy_engine_mode = 'all', 
                        rule = '', 
                        rule_obj = null, 
                        target = '', 
                        related = [
                            ''
                            ], 
                        related_obj = [
                            authentik_client.models.related_target.RelatedTarget(
                                verbose_name = '', 
                                verbose_name_plural = '', 
                                meta_model_name = '', 
                                pbm_uuid = '', 
                                label = '', )
                            ], 
                        expiry_pending = '', 
                        expiry_granted_max = '', )
                    ],
                autocomplete = {
                    'key' : null
                    }
            )
        else:
            return PaginatedRequestRuleBindingList(
                pagination = authentik_client.models.pagination.Pagination(
                    next = 1.337, 
                    previous = 1.337, 
                    count = 1.337, 
                    current = 1.337, 
                    total_pages = 1.337, 
                    start_index = 1.337, 
                    end_index = 1.337, ),
                results = [
                    authentik_client.models.request_rule_binding.RequestRuleBinding(
                        uuid = '', 
                        pbm_uuid = '', 
                        policy_engine_mode = 'all', 
                        rule = '', 
                        rule_obj = null, 
                        target = '', 
                        related = [
                            ''
                            ], 
                        related_obj = [
                            authentik_client.models.related_target.RelatedTarget(
                                verbose_name = '', 
                                verbose_name_plural = '', 
                                meta_model_name = '', 
                                pbm_uuid = '', 
                                label = '', )
                            ], 
                        expiry_pending = '', 
                        expiry_granted_max = '', )
                    ],
                autocomplete = {
                    'key' : null
                    },
        )
        """

    def testPaginatedRequestRuleBindingList(self):
        """Test PaginatedRequestRuleBindingList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
