# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.5.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.paginated_google_chrome_connector_list import PaginatedGoogleChromeConnectorList

class TestPaginatedGoogleChromeConnectorList(unittest.TestCase):
    """PaginatedGoogleChromeConnectorList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedGoogleChromeConnectorList:
        """Test PaginatedGoogleChromeConnectorList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedGoogleChromeConnectorList`
        """
        model = PaginatedGoogleChromeConnectorList()
        if include_optional:
            return PaginatedGoogleChromeConnectorList(
                pagination = authentik_client.models.pagination.Pagination(
                    next = 1.337, 
                    previous = 1.337, 
                    count = 1.337, 
                    current = 1.337, 
                    total_pages = 1.337, 
                    start_index = 1.337, 
                    end_index = 1.337, ),
                results = [
                    authentik_client.models.google_chrome_connector.GoogleChromeConnector(
                        connector_uuid = '', 
                        name = '', 
                        enabled = True, 
                        component = '', 
                        verbose_name = '', 
                        verbose_name_plural = '', 
                        meta_model_name = '', 
                        credentials = {
                            'key' : null
                            }, 
                        chrome_url = '', )
                    ],
                autocomplete = {
                    'key' : null
                    }
            )
        else:
            return PaginatedGoogleChromeConnectorList(
                pagination = authentik_client.models.pagination.Pagination(
                    next = 1.337, 
                    previous = 1.337, 
                    count = 1.337, 
                    current = 1.337, 
                    total_pages = 1.337, 
                    start_index = 1.337, 
                    end_index = 1.337, ),
                results = [
                    authentik_client.models.google_chrome_connector.GoogleChromeConnector(
                        connector_uuid = '', 
                        name = '', 
                        enabled = True, 
                        component = '', 
                        verbose_name = '', 
                        verbose_name_plural = '', 
                        meta_model_name = '', 
                        credentials = {
                            'key' : null
                            }, 
                        chrome_url = '', )
                    ],
                autocomplete = {
                    'key' : null
                    },
        )
        """

    def testPaginatedGoogleChromeConnectorList(self):
        """Test PaginatedGoogleChromeConnectorList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
