# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.5.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.grant_types_enum import GrantTypesEnum

class TestGrantTypesEnum(unittest.TestCase):
    """GrantTypesEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGrantTypesEnum(self):
        """Test GrantTypesEnum"""
        # inst = GrantTypesEnum()

if __name__ == '__main__':
    unittest.main()
