# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.8.0
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.resume_on_match_failures_enum import ResumeOnMatchFailuresEnum

class TestResumeOnMatchFailuresEnum(unittest.TestCase):
    """ResumeOnMatchFailuresEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResumeOnMatchFailuresEnum(self):
        """Test ResumeOnMatchFailuresEnum"""
        # inst = ResumeOnMatchFailuresEnum()

if __name__ == '__main__':
    unittest.main()
