# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.5.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.invitation_send_email_request import InvitationSendEmailRequest

class TestInvitationSendEmailRequest(unittest.TestCase):
    """InvitationSendEmailRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InvitationSendEmailRequest:
        """Test InvitationSendEmailRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InvitationSendEmailRequest`
        """
        model = InvitationSendEmailRequest()
        if include_optional:
            return InvitationSendEmailRequest(
                email_addresses = [
                    null
                    ],
                cc_addresses = [
                    null
                    ],
                bcc_addresses = [
                    null
                    ],
                template = 'invitation'
            )
        else:
            return InvitationSendEmailRequest(
                email_addresses = [
                    null
                    ],
        )
        """

    def testInvitationSendEmailRequest(self):
        """Test InvitationSendEmailRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
