# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.8.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.object_attribute_request import ObjectAttributeRequest

class TestObjectAttributeRequest(unittest.TestCase):
    """ObjectAttributeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ObjectAttributeRequest:
        """Test ObjectAttributeRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ObjectAttributeRequest`
        """
        model = ObjectAttributeRequest()
        if include_optional:
            return ObjectAttributeRequest(
                object_type = '0',
                enabled = True,
                key = '0',
                label = '0',
                regex = '',
                type = 'text',
                group = '',
                managed = '0',
                is_unique = True,
                is_required = True
            )
        else:
            return ObjectAttributeRequest(
                object_type = '0',
                key = '0',
                label = '0',
                type = 'text',
        )
        """

    def testObjectAttributeRequest(self):
        """Test ObjectAttributeRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
