# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.8.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.request_rule_request import RequestRuleRequest

class TestRequestRuleRequest(unittest.TestCase):
    """RequestRuleRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestRuleRequest:
        """Test RequestRuleRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestRuleRequest`
        """
        model = RequestRuleRequest()
        if include_optional:
            return RequestRuleRequest(
                uuid = '',
                policy_engine_mode = 'all',
                name = '0',
                notification_transports = [
                    ''
                    ],
                notification_mode = 'all',
                min_reviewers = 0,
                min_reviewers_is_per_group = True,
                request_flow = ''
            )
        else:
            return RequestRuleRequest(
                name = '0',
        )
        """

    def testRequestRuleRequest(self):
        """Test RequestRuleRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
