# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.2.0-rc2
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.paginated_lifecycle_rule_list import PaginatedLifecycleRuleList

class TestPaginatedLifecycleRuleList(unittest.TestCase):
    """PaginatedLifecycleRuleList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedLifecycleRuleList:
        """Test PaginatedLifecycleRuleList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedLifecycleRuleList`
        """
        model = PaginatedLifecycleRuleList()
        if include_optional:
            return PaginatedLifecycleRuleList(
                pagination = authentik_client.models.pagination.Pagination(
                    next = 1.337, 
                    previous = 1.337, 
                    count = 1.337, 
                    current = 1.337, 
                    total_pages = 1.337, 
                    start_index = 1.337, 
                    end_index = 1.337, ),
                results = [
                    authentik_client.models.lifecycle_rule.LifecycleRule(
                        id = '', 
                        name = '', 
                        content_type = 'authentik_core.application', 
                        object_id = '', 
                        interval = '', 
                        grace_period = '', 
                        reviewer_groups = [
                            ''
                            ], 
                        reviewer_groups_obj = [
                            authentik_client.models.reviewer_group.ReviewerGroup(
                                pk = '', 
                                name = '', )
                            ], 
                        min_reviewers = 0, 
                        min_reviewers_is_per_group = True, 
                        reviewers = [
                            ''
                            ], 
                        reviewers_obj = [
                            authentik_client.models.reviewer_user.ReviewerUser(
                                pk = 56, 
                                uuid = '', 
                                username = 'A', 
                                name = '', )
                            ], 
                        notification_transports = [
                            ''
                            ], 
                        target_verbose = '', )
                    ],
                autocomplete = {
                    'key' : null
                    }
            )
        else:
            return PaginatedLifecycleRuleList(
                pagination = authentik_client.models.pagination.Pagination(
                    next = 1.337, 
                    previous = 1.337, 
                    count = 1.337, 
                    current = 1.337, 
                    total_pages = 1.337, 
                    start_index = 1.337, 
                    end_index = 1.337, ),
                results = [
                    authentik_client.models.lifecycle_rule.LifecycleRule(
                        id = '', 
                        name = '', 
                        content_type = 'authentik_core.application', 
                        object_id = '', 
                        interval = '', 
                        grace_period = '', 
                        reviewer_groups = [
                            ''
                            ], 
                        reviewer_groups_obj = [
                            authentik_client.models.reviewer_group.ReviewerGroup(
                                pk = '', 
                                name = '', )
                            ], 
                        min_reviewers = 0, 
                        min_reviewers_is_per_group = True, 
                        reviewers = [
                            ''
                            ], 
                        reviewers_obj = [
                            authentik_client.models.reviewer_user.ReviewerUser(
                                pk = 56, 
                                uuid = '', 
                                username = 'A', 
                                name = '', )
                            ], 
                        notification_transports = [
                            ''
                            ], 
                        target_verbose = '', )
                    ],
                autocomplete = {
                    'key' : null
                    },
        )
        """

    def testPaginatedLifecycleRuleList(self):
        """Test PaginatedLifecycleRuleList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
