# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.2.0-rc3
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.review_request import ReviewRequest

class TestReviewRequest(unittest.TestCase):
    """ReviewRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReviewRequest:
        """Test ReviewRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReviewRequest`
        """
        model = ReviewRequest()
        if include_optional:
            return ReviewRequest(
                iteration = '',
                note = '0'
            )
        else:
            return ReviewRequest(
                iteration = '',
        )
        """

    def testReviewRequest(self):
        """Test ReviewRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
