# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.2.0-rc4
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.reviewer_group import ReviewerGroup

class TestReviewerGroup(unittest.TestCase):
    """ReviewerGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReviewerGroup:
        """Test ReviewerGroup
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReviewerGroup`
        """
        model = ReviewerGroup()
        if include_optional:
            return ReviewerGroup(
                pk = '',
                name = ''
            )
        else:
            return ReviewerGroup(
                pk = '',
                name = '',
        )
        """

    def testReviewerGroup(self):
        """Test ReviewerGroup"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
