# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.8.0-rc7
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.api.agents_api import AgentsApi


class TestAgentsApi(unittest.TestCase):
    """AgentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AgentsApi()

    def tearDown(self) -> None:
        pass

    def test_agents_agents_create(self) -> None:
        """Test case for agents_agents_create

        """
        pass

    def test_agents_agents_destroy(self) -> None:
        """Test case for agents_agents_destroy

        """
        pass

    def test_agents_agents_list(self) -> None:
        """Test case for agents_agents_list

        """
        pass

    def test_agents_agents_partial_update(self) -> None:
        """Test case for agents_agents_partial_update

        """
        pass

    def test_agents_agents_retrieve(self) -> None:
        """Test case for agents_agents_retrieve

        """
        pass

    def test_agents_agents_update(self) -> None:
        """Test case for agents_agents_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
