# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.5.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.logout_url import LogoutURL

class TestLogoutURL(unittest.TestCase):
    """LogoutURL unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LogoutURL:
        """Test LogoutURL
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LogoutURL`
        """
        model = LogoutURL()
        if include_optional:
            return LogoutURL(
                url = '',
                provider_name = '',
                binding = '',
                saml_request = '',
                saml_response = '',
                saml_relay_state = ''
            )
        else:
            return LogoutURL(
                url = '',
        )
        """

    def testLogoutURL(self):
        """Test LogoutURL"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
