# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.8.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.grant_type_enum import GrantTypeEnum

class TestGrantTypeEnum(unittest.TestCase):
    """GrantTypeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGrantTypeEnum(self):
        """Test GrantTypeEnum"""
        # inst = GrantTypeEnum()

if __name__ == '__main__':
    unittest.main()
