# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.8.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.patched_request_rule_binding_request import PatchedRequestRuleBindingRequest

class TestPatchedRequestRuleBindingRequest(unittest.TestCase):
    """PatchedRequestRuleBindingRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PatchedRequestRuleBindingRequest:
        """Test PatchedRequestRuleBindingRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PatchedRequestRuleBindingRequest`
        """
        model = PatchedRequestRuleBindingRequest()
        if include_optional:
            return PatchedRequestRuleBindingRequest(
                uuid = '',
                policy_engine_mode = 'all',
                rule = '',
                target = '',
                expiry_pending = '0',
                expiry_granted_max = '0'
            )
        else:
            return PatchedRequestRuleBindingRequest(
        )
        """

    def testPatchedRequestRuleBindingRequest(self):
        """Test PatchedRequestRuleBindingRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
