# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.2.0-rc4
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.lifecycle_rule_request import LifecycleRuleRequest

class TestLifecycleRuleRequest(unittest.TestCase):
    """LifecycleRuleRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LifecycleRuleRequest:
        """Test LifecycleRuleRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LifecycleRuleRequest`
        """
        model = LifecycleRuleRequest()
        if include_optional:
            return LifecycleRuleRequest(
                name = '0',
                content_type = 'authentik_core.application',
                object_id = '0',
                interval = '0',
                grace_period = '0',
                reviewer_groups = [
                    ''
                    ],
                min_reviewers = 0,
                min_reviewers_is_per_group = True,
                reviewers = [
                    ''
                    ],
                notification_transports = [
                    ''
                    ]
            )
        else:
            return LifecycleRuleRequest(
                name = '0',
                content_type = 'authentik_core.application',
                reviewers = [
                    ''
                    ],
        )
        """

    def testLifecycleRuleRequest(self):
        """Test LifecycleRuleRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
