# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.8.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.grant_request import GrantRequest

class TestGrantRequest(unittest.TestCase):
    """GrantRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GrantRequest:
        """Test GrantRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GrantRequest`
        """
        model = GrantRequest()
        if include_optional:
            return GrantRequest(
                created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_by = authentik_client.models.partial_user.PartialUser(
                    pk = 56, 
                    username = 'A', 
                    name = '', 
                    is_active = True, 
                    last_login = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    email = '', 
                    attributes = {
                        'key' : null
                        }, 
                    uid = '', ),
                requester_data = {
                    'key' : null
                    },
                fulfiller_data = {
                    'key' : null
                    },
                revoked_by = authentik_client.models.partial_user.PartialUser(
                    pk = 56, 
                    username = 'A', 
                    name = '', 
                    is_active = True, 
                    last_login = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    email = '', 
                    attributes = {
                        'key' : null
                        }, 
                    uid = '', ),
                is_active = True,
                expires = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                status = 'created',
                targets = [
                    ''
                    ],
                target_objs = [
                    authentik_client.models.requestable_target.RequestableTarget(
                        verbose_name = '', 
                        verbose_name_plural = '', 
                        meta_model_name = '', 
                        pbm_uuid = '', 
                        label = '', 
                        parent = null, )
                    ],
                uuid = ''
            )
        else:
            return GrantRequest(
                created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_by = authentik_client.models.partial_user.PartialUser(
                    pk = 56, 
                    username = 'A', 
                    name = '', 
                    is_active = True, 
                    last_login = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    email = '', 
                    attributes = {
                        'key' : null
                        }, 
                    uid = '', ),
                revoked_by = authentik_client.models.partial_user.PartialUser(
                    pk = 56, 
                    username = 'A', 
                    name = '', 
                    is_active = True, 
                    last_login = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    email = '', 
                    attributes = {
                        'key' : null
                        }, 
                    uid = '', ),
                is_active = True,
                status = 'created',
                targets = [
                    ''
                    ],
                target_objs = [
                    authentik_client.models.requestable_target.RequestableTarget(
                        verbose_name = '', 
                        verbose_name_plural = '', 
                        meta_model_name = '', 
                        pbm_uuid = '', 
                        label = '', 
                        parent = null, )
                    ],
        )
        """

    def testGrantRequest(self):
        """Test GrantRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
