# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.5.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.certificate_key_pair_key_type_enum import CertificateKeyPairKeyTypeEnum

class TestCertificateKeyPairKeyTypeEnum(unittest.TestCase):
    """CertificateKeyPairKeyTypeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCertificateKeyPairKeyTypeEnum(self):
        """Test CertificateKeyPairKeyTypeEnum"""
        # inst = CertificateKeyPairKeyTypeEnum()

if __name__ == '__main__':
    unittest.main()
