# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.8.0-rc7
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.agent_grant_request_created import AgentGrantRequestCreated

class TestAgentGrantRequestCreated(unittest.TestCase):
    """AgentGrantRequestCreated unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentGrantRequestCreated:
        """Test AgentGrantRequestCreated
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentGrantRequestCreated`
        """
        model = AgentGrantRequestCreated()
        if include_optional:
            return AgentGrantRequestCreated(
                grant_request = authentik_client.models.grant_request.GrantRequest(
                    created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    created_by = null, 
                    requester_data = {
                        'key' : null
                        }, 
                    fulfiller_data = {
                        'key' : null
                        }, 
                    revoked_by = null, 
                    agent_owner = null, 
                    is_active = True, 
                    expires = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    status = null, 
                    targets = [
                        ''
                        ], 
                    target_objs = [
                        authentik_client.models.requestable_target.RequestableTarget(
                            verbose_name = '', 
                            verbose_name_plural = '', 
                            meta_model_name = '', 
                            pbm_uuid = '', 
                            label = '', 
                            parent = null, )
                        ], 
                    uuid = '', ),
                fulfill_url = ''
            )
        else:
            return AgentGrantRequestCreated(
                grant_request = authentik_client.models.grant_request.GrantRequest(
                    created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    created_by = null, 
                    requester_data = {
                        'key' : null
                        }, 
                    fulfiller_data = {
                        'key' : null
                        }, 
                    revoked_by = null, 
                    agent_owner = null, 
                    is_active = True, 
                    expires = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    status = null, 
                    targets = [
                        ''
                        ], 
                    target_objs = [
                        authentik_client.models.requestable_target.RequestableTarget(
                            verbose_name = '', 
                            verbose_name_plural = '', 
                            meta_model_name = '', 
                            pbm_uuid = '', 
                            label = '', 
                            parent = null, )
                        ], 
                    uuid = '', ),
                fulfill_url = '',
        )
        """

    def testAgentGrantRequestCreated(self):
        """Test AgentGrantRequestCreated"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
