# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.8.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.request_rule_binding import RequestRuleBinding

class TestRequestRuleBinding(unittest.TestCase):
    """RequestRuleBinding unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestRuleBinding:
        """Test RequestRuleBinding
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestRuleBinding`
        """
        model = RequestRuleBinding()
        if include_optional:
            return RequestRuleBinding(
                uuid = '',
                pbm_uuid = '',
                policy_engine_mode = 'all',
                rule = '',
                rule_obj = authentik_client.models.request_rule.RequestRule(
                    uuid = '', 
                    pbm_uuid = '', 
                    policy_engine_mode = 'all', 
                    name = '', 
                    targets = [
                        ''
                        ], 
                    notification_transports = [
                        ''
                        ], 
                    notification_mode = 'all', 
                    min_reviewers = 0, 
                    min_reviewers_is_per_group = True, 
                    request_flow = '', ),
                target = '',
                related = [
                    ''
                    ],
                related_obj = [
                    authentik_client.models.related_target.RelatedTarget(
                        verbose_name = '', 
                        verbose_name_plural = '', 
                        meta_model_name = '', 
                        pbm_uuid = '', 
                        label = '', )
                    ],
                expiry_pending = '',
                expiry_granted_max = ''
            )
        else:
            return RequestRuleBinding(
                pbm_uuid = '',
                rule = '',
                rule_obj = authentik_client.models.request_rule.RequestRule(
                    uuid = '', 
                    pbm_uuid = '', 
                    policy_engine_mode = 'all', 
                    name = '', 
                    targets = [
                        ''
                        ], 
                    notification_transports = [
                        ''
                        ], 
                    notification_mode = 'all', 
                    min_reviewers = 0, 
                    min_reviewers_is_per_group = True, 
                    request_flow = '', ),
                target = '',
                related = [
                    ''
                    ],
                related_obj = [
                    authentik_client.models.related_target.RelatedTarget(
                        verbose_name = '', 
                        verbose_name_plural = '', 
                        meta_model_name = '', 
                        pbm_uuid = '', 
                        label = '', )
                    ],
        )
        """

    def testRequestRuleBinding(self):
        """Test RequestRuleBinding"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
