# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.2.0-rc4
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.task_state_enum import TaskStateEnum

class TestTaskStateEnum(unittest.TestCase):
    """TaskStateEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTaskStateEnum(self):
        """Test TaskStateEnum"""
        # inst = TaskStateEnum()

if __name__ == '__main__':
    unittest.main()
