# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.5.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.task_status_enum import TaskStatusEnum

class TestTaskStatusEnum(unittest.TestCase):
    """TaskStatusEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTaskStatusEnum(self):
        """Test TaskStatusEnum"""
        # inst = TaskStatusEnum()

if __name__ == '__main__':
    unittest.main()
