# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.8.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.patched_request_rule_child_binding_request import PatchedRequestRuleChildBindingRequest

class TestPatchedRequestRuleChildBindingRequest(unittest.TestCase):
    """PatchedRequestRuleChildBindingRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PatchedRequestRuleChildBindingRequest:
        """Test PatchedRequestRuleChildBindingRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PatchedRequestRuleChildBindingRequest`
        """
        model = PatchedRequestRuleChildBindingRequest()
        if include_optional:
            return PatchedRequestRuleChildBindingRequest(
                uuid = '',
                binding = '',
                target = ''
            )
        else:
            return PatchedRequestRuleChildBindingRequest(
        )
        """

    def testPatchedRequestRuleChildBindingRequest(self):
        """Test PatchedRequestRuleChildBindingRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
