# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.8.0-rc7
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.agent_grant_request_create_request import AgentGrantRequestCreateRequest

class TestAgentGrantRequestCreateRequest(unittest.TestCase):
    """AgentGrantRequestCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentGrantRequestCreateRequest:
        """Test AgentGrantRequestCreateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentGrantRequestCreateRequest`
        """
        model = AgentGrantRequestCreateRequest()
        if include_optional:
            return AgentGrantRequestCreateRequest(
                pbms = [
                    ''
                    ]
            )
        else:
            return AgentGrantRequestCreateRequest(
                pbms = [
                    ''
                    ],
        )
        """

    def testAgentGrantRequestCreateRequest(self):
        """Test AgentGrantRequestCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
