# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.8.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.paginated_o_auth2_dynamic_client_registration_list import PaginatedOAuth2DynamicClientRegistrationList

class TestPaginatedOAuth2DynamicClientRegistrationList(unittest.TestCase):
    """PaginatedOAuth2DynamicClientRegistrationList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedOAuth2DynamicClientRegistrationList:
        """Test PaginatedOAuth2DynamicClientRegistrationList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedOAuth2DynamicClientRegistrationList`
        """
        model = PaginatedOAuth2DynamicClientRegistrationList()
        if include_optional:
            return PaginatedOAuth2DynamicClientRegistrationList(
                pagination = authentik_client.models.pagination.Pagination(
                    next = 1.337, 
                    previous = 1.337, 
                    count = 1.337, 
                    current = 1.337, 
                    total_pages = 1.337, 
                    start_index = 1.337, 
                    end_index = 1.337, ),
                results = [
                    authentik_client.models.o_auth2_dynamic_client_registration.OAuth2DynamicClientRegistration(
                        pbm_uuid = '', 
                        provider = 56, 
                        default_application_group = '', 
                        override_authorization_flow = '', 
                        override_invalidation_flow = '', 
                        override_property_mappings = [
                            ''
                            ], 
                        access_token_validity = '', 
                        refresh_token_validity = '', 
                        allowed_grant_types = [
                            'authorization_code'
                            ], 
                        policy_engine_mode = 'all', )
                    ],
                autocomplete = {
                    'key' : null
                    }
            )
        else:
            return PaginatedOAuth2DynamicClientRegistrationList(
                pagination = authentik_client.models.pagination.Pagination(
                    next = 1.337, 
                    previous = 1.337, 
                    count = 1.337, 
                    current = 1.337, 
                    total_pages = 1.337, 
                    start_index = 1.337, 
                    end_index = 1.337, ),
                results = [
                    authentik_client.models.o_auth2_dynamic_client_registration.OAuth2DynamicClientRegistration(
                        pbm_uuid = '', 
                        provider = 56, 
                        default_application_group = '', 
                        override_authorization_flow = '', 
                        override_invalidation_flow = '', 
                        override_property_mappings = [
                            ''
                            ], 
                        access_token_validity = '', 
                        refresh_token_validity = '', 
                        allowed_grant_types = [
                            'authorization_code'
                            ], 
                        policy_engine_mode = 'all', )
                    ],
                autocomplete = {
                    'key' : null
                    },
        )
        """

    def testPaginatedOAuth2DynamicClientRegistrationList(self):
        """Test PaginatedOAuth2DynamicClientRegistrationList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
