# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.5.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.lang_enum import LangEnum

class TestLangEnum(unittest.TestCase):
    """LangEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLangEnum(self):
        """Test LangEnum"""
        # inst = LangEnum()

if __name__ == '__main__':
    unittest.main()
