# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.8.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_client.models.object_attribute import ObjectAttribute

class TestObjectAttribute(unittest.TestCase):
    """ObjectAttribute unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ObjectAttribute:
        """Test ObjectAttribute
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ObjectAttribute`
        """
        model = ObjectAttribute()
        if include_optional:
            return ObjectAttribute(
                pk = '',
                object_type = '',
                object_type_obj = authentik_client.models.content_type.ContentType(
                    id = 56, 
                    app_label = '', 
                    model = '', 
                    verbose_name_plural = '', 
                    fully_qualified_model = '', ),
                enabled = True,
                created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                key = '',
                label = '',
                last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                regex = '',
                type = 'text',
                group = '',
                managed = '',
                is_unique = True,
                is_required = True
            )
        else:
            return ObjectAttribute(
                pk = '',
                object_type = '',
                object_type_obj = authentik_client.models.content_type.ContentType(
                    id = 56, 
                    app_label = '', 
                    model = '', 
                    verbose_name_plural = '', 
                    fully_qualified_model = '', ),
                created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                key = '',
                label = '',
                last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                type = 'text',
        )
        """

    def testObjectAttribute(self):
        """Test ObjectAttribute"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
