---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - rissson
  - package-ecosystem: "docker-compose"
    directory: "/scripts"
    schedule:
      interval: "daily"
    assignees:
      - rissson
