# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.5.5
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AccountLockdownStageRequest(BaseModel):
    """
    AccountLockdownStage Serializer
    """ # noqa: E501
    name: Annotated[str, Field(min_length=1, strict=True)]
    deactivate_user: Optional[StrictBool] = Field(default=None, description="Deactivate the user account (set is_active to False)")
    set_unusable_password: Optional[StrictBool] = Field(default=None, description="Set an unusable password for the user")
    delete_sessions: Optional[StrictBool] = Field(default=None, description="Delete all active sessions for the user")
    revoke_tokens: Optional[StrictBool] = Field(default=None, description="Revoke all tokens for the user (API, app password, recovery, verification, OAuth)")
    self_service_completion_flow: Optional[UUID] = Field(default=None, description="Flow to redirect users to after self-service lockdown. This flow should not require authentication since the user's session is deleted.")
    __properties: ClassVar[List[str]] = ["name", "deactivate_user", "set_unusable_password", "delete_sessions", "revoke_tokens", "self_service_completion_flow"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AccountLockdownStageRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if self_service_completion_flow (nullable) is None
        # and model_fields_set contains the field
        if self.self_service_completion_flow is None and "self_service_completion_flow" in self.model_fields_set:
            _dict['self_service_completion_flow'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AccountLockdownStageRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "deactivate_user": obj.get("deactivate_user"),
            "set_unusable_password": obj.get("set_unusable_password"),
            "delete_sessions": obj.get("delete_sessions"),
            "revoke_tokens": obj.get("revoke_tokens"),
            "self_service_completion_flow": obj.get("self_service_completion_flow")
        })
        return _obj


