# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.5.4
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AuthenticatedSessionUserAgentOs(BaseModel):
    """
    User agent os
    """ # noqa: E501
    family: StrictStr
    major: Optional[StrictStr]
    minor: Optional[StrictStr]
    patch: Optional[StrictStr]
    patch_minor: Optional[StrictStr]
    __properties: ClassVar[List[str]] = ["family", "major", "minor", "patch", "patch_minor"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AuthenticatedSessionUserAgentOs from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if major (nullable) is None
        # and model_fields_set contains the field
        if self.major is None and "major" in self.model_fields_set:
            _dict['major'] = None

        # set to None if minor (nullable) is None
        # and model_fields_set contains the field
        if self.minor is None and "minor" in self.model_fields_set:
            _dict['minor'] = None

        # set to None if patch (nullable) is None
        # and model_fields_set contains the field
        if self.patch is None and "patch" in self.model_fields_set:
            _dict['patch'] = None

        # set to None if patch_minor (nullable) is None
        # and model_fields_set contains the field
        if self.patch_minor is None and "patch_minor" in self.model_fields_set:
            _dict['patch_minor'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AuthenticatedSessionUserAgentOs from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "family": obj.get("family"),
            "major": obj.get("major"),
            "minor": obj.get("minor"),
            "patch": obj.get("patch"),
            "patch_minor": obj.get("patch_minor")
        })
        return _obj


