# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.5.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ContentTypeEnum(str, Enum):
    """
    ContentTypeEnum
    """

    """
    allowed enum values
    """
    AUTHENTIK_CORE_DOT_APPLICATION = 'authentik_core.application'
    AUTHENTIK_CORE_DOT_GROUP = 'authentik_core.group'
    AUTHENTIK_RBAC_DOT_ROLE = 'authentik_rbac.role'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ContentTypeEnum from a JSON string"""
        return cls(json.loads(json_str))


