# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.2.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self

class FleetConnectorRequest(BaseModel):
    """
    FleetConnector Serializer
    """ # noqa: E501
    connector_uuid: Optional[UUID] = None
    name: Annotated[str, Field(min_length=1, strict=True)]
    enabled: Optional[StrictBool] = None
    url: Annotated[str, Field(min_length=1, strict=True, max_length=200)]
    token: Annotated[str, Field(min_length=1, strict=True)]
    headers_mapping: Optional[UUID] = Field(default=None, description="Configure additional headers to be sent. Mapping should return a dictionary of key-value pairs")
    map_users: Optional[StrictBool] = None
    map_teams_access_group: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["connector_uuid", "name", "enabled", "url", "token", "headers_mapping", "map_users", "map_teams_access_group"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FleetConnectorRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if headers_mapping (nullable) is None
        # and model_fields_set contains the field
        if self.headers_mapping is None and "headers_mapping" in self.model_fields_set:
            _dict['headers_mapping'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FleetConnectorRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "connector_uuid": obj.get("connector_uuid"),
            "name": obj.get("name"),
            "enabled": obj.get("enabled"),
            "url": obj.get("url"),
            "token": obj.get("token"),
            "headers_mapping": obj.get("headers_mapping"),
            "map_users": obj.get("map_users"),
            "map_teams_access_group": obj.get("map_teams_access_group")
        })
        return _obj


