# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.5.4
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ForceBindingEnum(str, Enum):
    """
    ForceBindingEnum
    """

    """
    allowed enum values
    """
    URN_COLON_OASIS_COLON_NAMES_COLON_TC_COLON_SAML_COLON_2_DOT_0_COLON_BINDINGS_COLON_HTTP_MINUS_POST = 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'
    URN_COLON_OASIS_COLON_NAMES_COLON_TC_COLON_SAML_COLON_2_DOT_0_COLON_BINDINGS_COLON_HTTP_MINUS_REDIRECT = 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ForceBindingEnum from a JSON string"""
        return cls(json.loads(json_str))


