# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.8.0
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from authentik_client.models.partial_user import PartialUser
from authentik_client.models.request_status import RequestStatus
from authentik_client.models.requestable_target import RequestableTarget
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GrantRequest(BaseModel):
    """
    Mixin to validate that a valid enterprise license exists before allowing to save the object
    """ # noqa: E501
    created: datetime
    created_by: PartialUser
    requester_data: Optional[Dict[str, Any]] = None
    fulfiller_data: Optional[Dict[str, Any]] = None
    revoked_by: Optional[PartialUser]
    agent_owner: Optional[PartialUser]
    is_active: StrictBool
    expires: Optional[datetime] = None
    status: RequestStatus
    targets: List[UUID]
    target_objs: List[RequestableTarget]
    uuid: Optional[UUID] = None
    __properties: ClassVar[List[str]] = ["created", "created_by", "requester_data", "fulfiller_data", "revoked_by", "agent_owner", "is_active", "expires", "status", "targets", "target_objs", "uuid"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GrantRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "created",
            "created_by",
            "revoked_by",
            "agent_owner",
            "is_active",
            "status",
            "targets",
            "target_objs",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of created_by
        if self.created_by:
            _dict['created_by'] = self.created_by.to_dict()
        # override the default output from pydantic by calling `to_dict()` of revoked_by
        if self.revoked_by:
            _dict['revoked_by'] = self.revoked_by.to_dict()
        # override the default output from pydantic by calling `to_dict()` of agent_owner
        if self.agent_owner:
            _dict['agent_owner'] = self.agent_owner.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in target_objs (list)
        _items = []
        if self.target_objs:
            for _item_target_objs in self.target_objs:
                if _item_target_objs:
                    _items.append(_item_target_objs.to_dict())
            _dict['target_objs'] = _items
        # set to None if revoked_by (nullable) is None
        # and model_fields_set contains the field
        if self.revoked_by is None and "revoked_by" in self.model_fields_set:
            _dict['revoked_by'] = None

        # set to None if agent_owner (nullable) is None
        # and model_fields_set contains the field
        if self.agent_owner is None and "agent_owner" in self.model_fields_set:
            _dict['agent_owner'] = None

        # set to None if expires (nullable) is None
        # and model_fields_set contains the field
        if self.expires is None and "expires" in self.model_fields_set:
            _dict['expires'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GrantRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created": obj.get("created"),
            "created_by": PartialUser.from_dict(obj["created_by"]) if obj.get("created_by") is not None else None,
            "requester_data": obj.get("requester_data"),
            "fulfiller_data": obj.get("fulfiller_data"),
            "revoked_by": PartialUser.from_dict(obj["revoked_by"]) if obj.get("revoked_by") is not None else None,
            "agent_owner": PartialUser.from_dict(obj["agent_owner"]) if obj.get("agent_owner") is not None else None,
            "is_active": obj.get("is_active"),
            "expires": obj.get("expires"),
            "status": obj.get("status"),
            "targets": obj.get("targets"),
            "target_objs": [RequestableTarget.from_dict(_item) for _item in obj["target_objs"]] if obj.get("target_objs") is not None else None,
            "uuid": obj.get("uuid")
        })
        return _obj


