# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.5.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class GrantTypesEnum(str, Enum):
    """
    GrantTypesEnum
    """

    """
    allowed enum values
    """
    AUTHORIZATION_CODE = 'authorization_code'
    IMPLICIT = 'implicit'
    HYBRID = 'hybrid'
    REFRESH_TOKEN = 'refresh_token'
    CLIENT_CREDENTIALS = 'client_credentials'
    PASSWORD = 'password'
    URN_COLON_IETF_COLON_PARAMS_COLON_OAUTH_COLON_GRANT_MINUS_TYPE_COLON_DEVICE_CODE = 'urn:ietf:params:oauth:grant-type:device_code'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GrantTypesEnum from a JSON string"""
        return cls(json.loads(json_str))


