# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.5.4
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class LangEnum(str, Enum):
    """
    LangEnum
    """

    """
    allowed enum values
    """
    AF = 'af'
    AR = 'ar'
    AR_MINUS_DZ = 'ar-dz'
    AST = 'ast'
    AZ = 'az'
    BE = 'be'
    BG = 'bg'
    BN = 'bn'
    BR = 'br'
    BS = 'bs'
    CA = 'ca'
    CKB = 'ckb'
    CS = 'cs'
    CY = 'cy'
    DA = 'da'
    DE = 'de'
    DSB = 'dsb'
    EL = 'el'
    EN = 'en'
    EN_MINUS_AU = 'en-au'
    EN_MINUS_GB = 'en-gb'
    EO = 'eo'
    ES = 'es'
    ES_MINUS_AR = 'es-ar'
    ES_MINUS_CO = 'es-co'
    ES_MINUS_MX = 'es-mx'
    ES_MINUS_NI = 'es-ni'
    ES_MINUS_VE = 'es-ve'
    ET = 'et'
    EU = 'eu'
    FA = 'fa'
    FI = 'fi'
    FR = 'fr'
    FY = 'fy'
    GA = 'ga'
    GD = 'gd'
    GL = 'gl'
    HE = 'he'
    HI = 'hi'
    HR = 'hr'
    HSB = 'hsb'
    HU = 'hu'
    HY = 'hy'
    IA = 'ia'
    ID = 'id'
    IG = 'ig'
    IO = 'io'
    IS = 'is'
    IT = 'it'
    JA = 'ja'
    KA = 'ka'
    KAB = 'kab'
    KK = 'kk'
    KM = 'km'
    KN = 'kn'
    KO = 'ko'
    KY = 'ky'
    LB = 'lb'
    LT = 'lt'
    LV = 'lv'
    MK = 'mk'
    ML = 'ml'
    MN = 'mn'
    MR = 'mr'
    MS = 'ms'
    MY = 'my'
    NB = 'nb'
    NE = 'ne'
    NL = 'nl'
    NN = 'nn'
    OS = 'os'
    PA = 'pa'
    PL = 'pl'
    PT = 'pt'
    PT_MINUS_BR = 'pt-br'
    RO = 'ro'
    RU = 'ru'
    SK = 'sk'
    SL = 'sl'
    SQ = 'sq'
    SR = 'sr'
    SR_MINUS_LATN = 'sr-latn'
    SV = 'sv'
    SW = 'sw'
    TA = 'ta'
    TE = 'te'
    TG = 'tg'
    TH = 'th'
    TK = 'tk'
    TR = 'tr'
    TT = 'tt'
    UDM = 'udm'
    UG = 'ug'
    UK = 'uk'
    UR = 'ur'
    UZ = 'uz'
    VI = 'vi'
    ZH_MINUS_HANS = 'zh-hans'
    ZH_MINUS_HANT = 'zh-hant'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of LangEnum from a JSON string"""
        return cls(json.loads(json_str))


