# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.5.3
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List
from uuid import UUID
from authentik_client.models.content_type_enum import ContentTypeEnum
from authentik_client.models.lifecycle_iteration_state_enum import LifecycleIterationStateEnum
from authentik_client.models.related_rule import RelatedRule
from authentik_client.models.review import Review
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class LifecycleIteration(BaseModel):
    """
    Mixin to validate that a valid enterprise license exists before allowing to save the object
    """ # noqa: E501
    id: UUID
    content_type: ContentTypeEnum
    object_id: StrictStr
    object_verbose: StrictStr
    object_admin_url: StrictStr
    state: LifecycleIterationStateEnum
    opened_on: datetime
    grace_period_end: datetime
    next_review_date: datetime
    reviews: List[Review]
    rule: RelatedRule
    user_can_review: StrictBool
    __properties: ClassVar[List[str]] = ["id", "content_type", "object_id", "object_verbose", "object_admin_url", "state", "opened_on", "grace_period_end", "next_review_date", "reviews", "rule", "user_can_review"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LifecycleIteration from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "object_id",
            "object_verbose",
            "object_admin_url",
            "state",
            "opened_on",
            "grace_period_end",
            "next_review_date",
            "reviews",
            "rule",
            "user_can_review",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in reviews (list)
        _items = []
        if self.reviews:
            for _item_reviews in self.reviews:
                if _item_reviews:
                    _items.append(_item_reviews.to_dict())
            _dict['reviews'] = _items
        # override the default output from pydantic by calling `to_dict()` of rule
        if self.rule:
            _dict['rule'] = self.rule.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LifecycleIteration from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "content_type": obj.get("content_type"),
            "object_id": obj.get("object_id"),
            "object_verbose": obj.get("object_verbose"),
            "object_admin_url": obj.get("object_admin_url"),
            "state": obj.get("state"),
            "opened_on": obj.get("opened_on"),
            "grace_period_end": obj.get("grace_period_end"),
            "next_review_date": obj.get("next_review_date"),
            "reviews": [Review.from_dict(_item) for _item in obj["reviews"]] if obj.get("reviews") is not None else None,
            "rule": RelatedRule.from_dict(obj["rule"]) if obj.get("rule") is not None else None,
            "user_can_review": obj.get("user_can_review")
        })
        return _obj


