# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.2.0-rc3
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from authentik_client.models.content_type_enum import ContentTypeEnum
from authentik_client.models.reviewer_group import ReviewerGroup
from authentik_client.models.reviewer_user import ReviewerUser
from typing import Optional, Set
from typing_extensions import Self

class LifecycleRule(BaseModel):
    """
    Mixin to validate that a valid enterprise license exists before allowing to save the object
    """ # noqa: E501
    id: UUID
    name: StrictStr
    content_type: ContentTypeEnum
    object_id: Optional[StrictStr] = None
    interval: Optional[StrictStr] = None
    grace_period: Optional[StrictStr] = None
    reviewer_groups: Optional[List[UUID]] = None
    reviewer_groups_obj: List[ReviewerGroup]
    min_reviewers: Optional[Annotated[int, Field(le=32767, strict=True, ge=0)]] = None
    min_reviewers_is_per_group: Optional[StrictBool] = None
    reviewers: List[UUID]
    reviewers_obj: List[ReviewerUser]
    notification_transports: Optional[List[UUID]] = Field(default=None, description="Select which transports should be used to notify the reviewers. If none are selected, the notification will only be shown in the authentik UI.")
    target_verbose: StrictStr
    __properties: ClassVar[List[str]] = ["id", "name", "content_type", "object_id", "interval", "grace_period", "reviewer_groups", "reviewer_groups_obj", "min_reviewers", "min_reviewers_is_per_group", "reviewers", "reviewers_obj", "notification_transports", "target_verbose"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LifecycleRule from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "reviewer_groups_obj",
            "reviewers_obj",
            "target_verbose",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in reviewer_groups_obj (list)
        _items = []
        if self.reviewer_groups_obj:
            for _item_reviewer_groups_obj in self.reviewer_groups_obj:
                if _item_reviewer_groups_obj:
                    _items.append(_item_reviewer_groups_obj.to_dict())
            _dict['reviewer_groups_obj'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in reviewers_obj (list)
        _items = []
        if self.reviewers_obj:
            for _item_reviewers_obj in self.reviewers_obj:
                if _item_reviewers_obj:
                    _items.append(_item_reviewers_obj.to_dict())
            _dict['reviewers_obj'] = _items
        # set to None if object_id (nullable) is None
        # and model_fields_set contains the field
        if self.object_id is None and "object_id" in self.model_fields_set:
            _dict['object_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LifecycleRule from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "content_type": obj.get("content_type"),
            "object_id": obj.get("object_id"),
            "interval": obj.get("interval"),
            "grace_period": obj.get("grace_period"),
            "reviewer_groups": obj.get("reviewer_groups"),
            "reviewer_groups_obj": [ReviewerGroup.from_dict(_item) for _item in obj["reviewer_groups_obj"]] if obj.get("reviewer_groups_obj") is not None else None,
            "min_reviewers": obj.get("min_reviewers"),
            "min_reviewers_is_per_group": obj.get("min_reviewers_is_per_group"),
            "reviewers": obj.get("reviewers"),
            "reviewers_obj": [ReviewerUser.from_dict(_item) for _item in obj["reviewers_obj"]] if obj.get("reviewers_obj") is not None else None,
            "notification_transports": obj.get("notification_transports"),
            "target_verbose": obj.get("target_verbose")
        })
        return _obj


