# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.5.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class LogoutURL(BaseModel):
    """
    Data for a single logout URL
    """ # noqa: E501
    url: StrictStr
    provider_name: Optional[StrictStr] = None
    binding: Optional[StrictStr] = None
    saml_request: Optional[StrictStr] = None
    saml_response: Optional[StrictStr] = None
    saml_relay_state: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["url", "provider_name", "binding", "saml_request", "saml_response", "saml_relay_state"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LogoutURL from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if provider_name (nullable) is None
        # and model_fields_set contains the field
        if self.provider_name is None and "provider_name" in self.model_fields_set:
            _dict['provider_name'] = None

        # set to None if binding (nullable) is None
        # and model_fields_set contains the field
        if self.binding is None and "binding" in self.model_fields_set:
            _dict['binding'] = None

        # set to None if saml_request (nullable) is None
        # and model_fields_set contains the field
        if self.saml_request is None and "saml_request" in self.model_fields_set:
            _dict['saml_request'] = None

        # set to None if saml_response (nullable) is None
        # and model_fields_set contains the field
        if self.saml_response is None and "saml_response" in self.model_fields_set:
            _dict['saml_response'] = None

        # set to None if saml_relay_state (nullable) is None
        # and model_fields_set contains the field
        if self.saml_relay_state is None and "saml_relay_state" in self.model_fields_set:
            _dict['saml_relay_state'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LogoutURL from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "url": obj.get("url"),
            "provider_name": obj.get("provider_name"),
            "binding": obj.get("binding"),
            "saml_request": obj.get("saml_request"),
            "saml_response": obj.get("saml_response"),
            "saml_relay_state": obj.get("saml_relay_state")
        })
        return _obj


