# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.8.1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from authentik_client.models.grant_type_enum import GrantTypeEnum
from authentik_client.models.policy_engine_mode import PolicyEngineMode
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class OAuth2DynamicClientRegistration(BaseModel):
    """
    Serializer for OAuth2DynamicClientRegistration
    """ # noqa: E501
    pbm_uuid: UUID
    provider: StrictInt
    default_application_group: Optional[StrictStr] = Field(default=None, description="Group to assign to automatically created applications.")
    override_authorization_flow: Optional[UUID] = Field(default=None, description="Authorization flow applied to dynamically registered clients.")
    override_invalidation_flow: Optional[UUID] = None
    override_property_mappings: Optional[List[UUID]] = Field(default=None, description="Scope mappings applied to dynamically registered clients.")
    access_token_validity: Optional[StrictStr] = Field(default=None, description="Maximum access token validity for registered clients (Format: hours=1;minutes=2;seconds=3).")
    refresh_token_validity: Optional[StrictStr] = Field(default=None, description="Maximum refresh token validity for registered clients (Format: hours=1;minutes=2;seconds=3).")
    allowed_grant_types: Optional[List[GrantTypeEnum]] = Field(default=None, description="If empty, all grant types are allowed.")
    policy_engine_mode: Optional[PolicyEngineMode] = None
    __properties: ClassVar[List[str]] = ["pbm_uuid", "provider", "default_application_group", "override_authorization_flow", "override_invalidation_flow", "override_property_mappings", "access_token_validity", "refresh_token_validity", "allowed_grant_types", "policy_engine_mode"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OAuth2DynamicClientRegistration from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "pbm_uuid",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if override_authorization_flow (nullable) is None
        # and model_fields_set contains the field
        if self.override_authorization_flow is None and "override_authorization_flow" in self.model_fields_set:
            _dict['override_authorization_flow'] = None

        # set to None if override_invalidation_flow (nullable) is None
        # and model_fields_set contains the field
        if self.override_invalidation_flow is None and "override_invalidation_flow" in self.model_fields_set:
            _dict['override_invalidation_flow'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OAuth2DynamicClientRegistration from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "pbm_uuid": obj.get("pbm_uuid"),
            "provider": obj.get("provider"),
            "default_application_group": obj.get("default_application_group"),
            "override_authorization_flow": obj.get("override_authorization_flow"),
            "override_invalidation_flow": obj.get("override_invalidation_flow"),
            "override_property_mappings": obj.get("override_property_mappings"),
            "access_token_validity": obj.get("access_token_validity"),
            "refresh_token_validity": obj.get("refresh_token_validity"),
            "allowed_grant_types": obj.get("allowed_grant_types"),
            "policy_engine_mode": obj.get("policy_engine_mode")
        })
        return _obj


