# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.8.1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from authentik_client.models.content_type import ContentType
from authentik_client.models.object_attribute_type_enum import ObjectAttributeTypeEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ObjectAttribute(BaseModel):
    """
    ObjectAttribute
    """ # noqa: E501
    pk: UUID
    object_type: StrictStr
    object_type_obj: ContentType
    enabled: Optional[StrictBool] = True
    created: datetime
    key: StrictStr
    label: StrictStr
    last_updated: datetime
    regex: Optional[StrictStr] = None
    type: ObjectAttributeTypeEnum
    group: Optional[StrictStr] = None
    managed: Optional[StrictStr] = Field(default=None, description="Objects that are managed by authentik. These objects are created and updated automatically. This flag only indicates that an object can be overwritten by migrations. You can still modify the objects via the API, but expect changes to be overwritten in a later update.")
    is_unique: Optional[StrictBool] = None
    is_required: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["pk", "object_type", "object_type_obj", "enabled", "created", "key", "label", "last_updated", "regex", "type", "group", "managed", "is_unique", "is_required"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ObjectAttribute from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "pk",
            "object_type_obj",
            "created",
            "last_updated",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of object_type_obj
        if self.object_type_obj:
            _dict['object_type_obj'] = self.object_type_obj.to_dict()
        # set to None if managed (nullable) is None
        # and model_fields_set contains the field
        if self.managed is None and "managed" in self.model_fields_set:
            _dict['managed'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ObjectAttribute from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "pk": obj.get("pk"),
            "object_type": obj.get("object_type"),
            "object_type_obj": ContentType.from_dict(obj["object_type_obj"]) if obj.get("object_type_obj") is not None else None,
            "enabled": obj.get("enabled") if obj.get("enabled") is not None else True,
            "created": obj.get("created"),
            "key": obj.get("key"),
            "label": obj.get("label"),
            "last_updated": obj.get("last_updated"),
            "regex": obj.get("regex"),
            "type": obj.get("type"),
            "group": obj.get("group"),
            "managed": obj.get("managed"),
            "is_unique": obj.get("is_unique"),
            "is_required": obj.get("is_required")
        })
        return _obj


