# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.8.1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from authentik_client.models.notification_mode_enum import NotificationModeEnum
from authentik_client.models.policy_engine_mode import PolicyEngineMode
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PatchedRequestRuleRequest(BaseModel):
    """
    Mixin to validate that a valid enterprise license exists before allowing to save the object
    """ # noqa: E501
    uuid: Optional[UUID] = None
    policy_engine_mode: Optional[PolicyEngineMode] = None
    name: Optional[Annotated[str, Field(min_length=1, strict=True)]] = None
    notification_transports: Optional[List[UUID]] = None
    notification_mode: Optional[NotificationModeEnum] = None
    min_reviewers: Optional[Annotated[int, Field(le=32767, strict=True, ge=0)]] = None
    min_reviewers_is_per_group: Optional[StrictBool] = None
    request_flow: Optional[UUID] = None
    __properties: ClassVar[List[str]] = ["uuid", "policy_engine_mode", "name", "notification_transports", "notification_mode", "min_reviewers", "min_reviewers_is_per_group", "request_flow"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PatchedRequestRuleRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if request_flow (nullable) is None
        # and model_fields_set contains the field
        if self.request_flow is None and "request_flow" in self.model_fields_set:
            _dict['request_flow'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PatchedRequestRuleRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "uuid": obj.get("uuid"),
            "policy_engine_mode": obj.get("policy_engine_mode"),
            "name": obj.get("name"),
            "notification_transports": obj.get("notification_transports"),
            "notification_mode": obj.get("notification_mode"),
            "min_reviewers": obj.get("min_reviewers"),
            "min_reviewers_is_per_group": obj.get("min_reviewers_is_per_group"),
            "request_flow": obj.get("request_flow")
        })
        return _obj


