# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.2.1-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from authentik_client.models.content_type_enum import ContentTypeEnum
from typing import Optional, Set
from typing_extensions import Self

class PatchedLifecycleRuleRequest(BaseModel):
    """
    Mixin to validate that a valid enterprise license exists before allowing to save the object
    """ # noqa: E501
    name: Optional[Annotated[str, Field(min_length=1, strict=True)]] = None
    content_type: Optional[ContentTypeEnum] = None
    object_id: Optional[Annotated[str, Field(min_length=1, strict=True)]] = None
    interval: Optional[Annotated[str, Field(min_length=1, strict=True)]] = None
    grace_period: Optional[Annotated[str, Field(min_length=1, strict=True)]] = None
    reviewer_groups: Optional[List[UUID]] = None
    min_reviewers: Optional[Annotated[int, Field(le=32767, strict=True, ge=0)]] = None
    min_reviewers_is_per_group: Optional[StrictBool] = None
    reviewers: Optional[List[UUID]] = None
    notification_transports: Optional[List[UUID]] = Field(default=None, description="Select which transports should be used to notify the reviewers. If none are selected, the notification will only be shown in the authentik UI.")
    __properties: ClassVar[List[str]] = ["name", "content_type", "object_id", "interval", "grace_period", "reviewer_groups", "min_reviewers", "min_reviewers_is_per_group", "reviewers", "notification_transports"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PatchedLifecycleRuleRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if object_id (nullable) is None
        # and model_fields_set contains the field
        if self.object_id is None and "object_id" in self.model_fields_set:
            _dict['object_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PatchedLifecycleRuleRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "content_type": obj.get("content_type"),
            "object_id": obj.get("object_id"),
            "interval": obj.get("interval"),
            "grace_period": obj.get("grace_period"),
            "reviewer_groups": obj.get("reviewer_groups"),
            "min_reviewers": obj.get("min_reviewers"),
            "min_reviewers_is_per_group": obj.get("min_reviewers_is_per_group"),
            "reviewers": obj.get("reviewers"),
            "notification_transports": obj.get("notification_transports")
        })
        return _obj


