# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.8.0
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from authentik_client.models.object_attribute_type_enum import ObjectAttributeTypeEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PatchedObjectAttributeRequest(BaseModel):
    """
    PatchedObjectAttributeRequest
    """ # noqa: E501
    object_type: Optional[Annotated[str, Field(min_length=1, strict=True)]] = None
    enabled: Optional[StrictBool] = True
    key: Optional[Annotated[str, Field(min_length=1, strict=True)]] = None
    label: Optional[Annotated[str, Field(min_length=1, strict=True)]] = None
    regex: Optional[StrictStr] = None
    type: Optional[ObjectAttributeTypeEnum] = None
    group: Optional[StrictStr] = None
    managed: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, description="Objects that are managed by authentik. These objects are created and updated automatically. This flag only indicates that an object can be overwritten by migrations. You can still modify the objects via the API, but expect changes to be overwritten in a later update.")
    is_unique: Optional[StrictBool] = None
    is_required: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["object_type", "enabled", "key", "label", "regex", "type", "group", "managed", "is_unique", "is_required"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PatchedObjectAttributeRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if managed (nullable) is None
        # and model_fields_set contains the field
        if self.managed is None and "managed" in self.model_fields_set:
            _dict['managed'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PatchedObjectAttributeRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "object_type": obj.get("object_type"),
            "enabled": obj.get("enabled") if obj.get("enabled") is not None else True,
            "key": obj.get("key"),
            "label": obj.get("label"),
            "regex": obj.get("regex"),
            "type": obj.get("type"),
            "group": obj.get("group"),
            "managed": obj.get("managed"),
            "is_unique": obj.get("is_unique"),
            "is_required": obj.get("is_required")
        })
        return _obj


