# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.8.1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from authentik_client.models.policy_engine_mode import PolicyEngineMode
from authentik_client.models.related_target import RelatedTarget
from authentik_client.models.request_rule import RequestRule
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class RequestRuleBinding(BaseModel):
    """
    Mixin to validate that a valid enterprise license exists before allowing to save the object
    """ # noqa: E501
    uuid: Optional[UUID] = None
    pbm_uuid: UUID
    policy_engine_mode: Optional[PolicyEngineMode] = None
    rule: UUID
    rule_obj: RequestRule
    target: UUID
    related: List[UUID]
    related_obj: List[RelatedTarget]
    expiry_pending: Optional[StrictStr] = Field(default=None, description="How long a request against this binding stays pending before it automatically lapses if not approved or denied.")
    expiry_granted_max: Optional[StrictStr] = Field(default=None, description="The maximum duration a grant approved against this binding can last.")
    __properties: ClassVar[List[str]] = ["uuid", "pbm_uuid", "policy_engine_mode", "rule", "rule_obj", "target", "related", "related_obj", "expiry_pending", "expiry_granted_max"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RequestRuleBinding from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "pbm_uuid",
            "rule_obj",
            "related",
            "related_obj",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of rule_obj
        if self.rule_obj:
            _dict['rule_obj'] = self.rule_obj.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in related_obj (list)
        _items = []
        if self.related_obj:
            for _item_related_obj in self.related_obj:
                if _item_related_obj:
                    _items.append(_item_related_obj.to_dict())
            _dict['related_obj'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RequestRuleBinding from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "uuid": obj.get("uuid"),
            "pbm_uuid": obj.get("pbm_uuid"),
            "policy_engine_mode": obj.get("policy_engine_mode"),
            "rule": obj.get("rule"),
            "rule_obj": RequestRule.from_dict(obj["rule_obj"]) if obj.get("rule_obj") is not None else None,
            "target": obj.get("target"),
            "related": obj.get("related"),
            "related_obj": [RelatedTarget.from_dict(_item) for _item in obj["related_obj"]] if obj.get("related_obj") is not None else None,
            "expiry_pending": obj.get("expiry_pending"),
            "expiry_granted_max": obj.get("expiry_granted_max")
        })
        return _obj


