# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.8.1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SamlVersionEnum(str, Enum):
    """
    SamlVersionEnum
    """

    """
    allowed enum values
    """
    ENUM_1_DOT_1 = '1.1'
    ENUM_2_DOT_0 = '2.0'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SamlVersionEnum from a JSON string"""
        return cls(json.loads(json_str))


