# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.5.4
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from authentik_client.models.provider import Provider
from authentik_client.models.token import Token
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SSFProvider(BaseModel):
    """
    SSFProvider Serializer
    """ # noqa: E501
    pk: StrictInt
    name: StrictStr
    component: StrictStr = Field(description="Get object component so that we know how to edit the object")
    verbose_name: StrictStr = Field(description="Return object's verbose_name")
    verbose_name_plural: StrictStr = Field(description="Return object's plural verbose_name")
    meta_model_name: StrictStr = Field(description="Return internal model name")
    signing_key: UUID = Field(description="Key used to sign the SSF Events.")
    token_obj: Token
    oidc_auth_providers: Optional[List[StrictInt]] = None
    oidc_auth_providers_obj: List[Provider]
    ssf_url: Optional[StrictStr]
    event_retention: Optional[StrictStr] = None
    push_verify_certificates: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["pk", "name", "component", "verbose_name", "verbose_name_plural", "meta_model_name", "signing_key", "token_obj", "oidc_auth_providers", "oidc_auth_providers_obj", "ssf_url", "event_retention", "push_verify_certificates"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SSFProvider from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "pk",
            "component",
            "verbose_name",
            "verbose_name_plural",
            "meta_model_name",
            "token_obj",
            "oidc_auth_providers_obj",
            "ssf_url",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of token_obj
        if self.token_obj:
            _dict['token_obj'] = self.token_obj.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in oidc_auth_providers_obj (list)
        _items = []
        if self.oidc_auth_providers_obj:
            for _item_oidc_auth_providers_obj in self.oidc_auth_providers_obj:
                if _item_oidc_auth_providers_obj:
                    _items.append(_item_oidc_auth_providers_obj.to_dict())
            _dict['oidc_auth_providers_obj'] = _items
        # set to None if ssf_url (nullable) is None
        # and model_fields_set contains the field
        if self.ssf_url is None and "ssf_url" in self.model_fields_set:
            _dict['ssf_url'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SSFProvider from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "pk": obj.get("pk"),
            "name": obj.get("name"),
            "component": obj.get("component"),
            "verbose_name": obj.get("verbose_name"),
            "verbose_name_plural": obj.get("verbose_name_plural"),
            "meta_model_name": obj.get("meta_model_name"),
            "signing_key": obj.get("signing_key"),
            "token_obj": Token.from_dict(obj["token_obj"]) if obj.get("token_obj") is not None else None,
            "oidc_auth_providers": obj.get("oidc_auth_providers"),
            "oidc_auth_providers_obj": [Provider.from_dict(_item) for _item in obj["oidc_auth_providers_obj"]] if obj.get("oidc_auth_providers_obj") is not None else None,
            "ssf_url": obj.get("ssf_url"),
            "event_retention": obj.get("event_retention"),
            "push_verify_certificates": obj.get("push_verify_certificates")
        })
        return _obj


