# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.8.1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from authentik_client.models.offboarding_action_enum import OffboardingActionEnum
from authentik_client.models.offboarding_status_enum import OffboardingStatusEnum
from authentik_client.models.partial_user import PartialUser
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UserOffboarding(BaseModel):
    """
    Mixin to validate that a valid enterprise license exists before allowing to save the object
    """ # noqa: E501
    id: UUID
    user: StrictInt
    user_obj: PartialUser
    scheduled_at: datetime = Field(description="Absolute time at which the offboarding action is executed.")
    action: Optional[OffboardingActionEnum] = None
    revoke_sessions: Optional[StrictBool] = Field(default=None, description="Revoke all of the user's sessions when offboarding.")
    revoke_tokens: Optional[StrictBool] = Field(default=None, description="Revoke all of the user's tokens when offboarding.")
    status: OffboardingStatusEnum
    created_by_obj: PartialUser
    created_at: datetime
    executed_at: Optional[datetime]
    __properties: ClassVar[List[str]] = ["id", "user", "user_obj", "scheduled_at", "action", "revoke_sessions", "revoke_tokens", "status", "created_by_obj", "created_at", "executed_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserOffboarding from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "user_obj",
            "status",
            "created_by_obj",
            "created_at",
            "executed_at",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of user_obj
        if self.user_obj:
            _dict['user_obj'] = self.user_obj.to_dict()
        # override the default output from pydantic by calling `to_dict()` of created_by_obj
        if self.created_by_obj:
            _dict['created_by_obj'] = self.created_by_obj.to_dict()
        # set to None if executed_at (nullable) is None
        # and model_fields_set contains the field
        if self.executed_at is None and "executed_at" in self.model_fields_set:
            _dict['executed_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserOffboarding from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "user": obj.get("user"),
            "user_obj": PartialUser.from_dict(obj["user_obj"]) if obj.get("user_obj") is not None else None,
            "scheduled_at": obj.get("scheduled_at"),
            "action": obj.get("action"),
            "revoke_sessions": obj.get("revoke_sessions"),
            "revoke_tokens": obj.get("revoke_tokens"),
            "status": obj.get("status"),
            "created_by_obj": PartialUser.from_dict(obj["created_by_obj"]) if obj.get("created_by_obj") is not None else None,
            "created_at": obj.get("created_at"),
            "executed_at": obj.get("executed_at")
        })
        return _obj


