# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2026.2.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class VendorEnum(str, Enum):
    """
    VendorEnum
    """

    """
    allowed enum values
    """
    GOAUTHENTIK_DOT_IO_SLASH_AT_MERGED = 'goauthentik.io/@merged'
    GOAUTHENTIK_DOT_IO_SLASH_PLATFORM = 'goauthentik.io/platform'
    FLEETDM_DOT_COM = 'fleetdm.com'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of VendorEnum from a JSON string"""
        return cls(json.loads(json_str))


