---
services:
  diff:
    image: docker.io/openapitools/openapi-diff:2.1.2
    restart: never
    volumes:
      - ../:/local

  gen:
    image: docker.io/openapitools/openapi-generator-cli:v7.15.0
    restart: never
    volumes:
      - ../:/local
